import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import SessionProviderWrapper from "./components/SessionProviderWrapper";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import Link from "next/link";






const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QuizCraft AI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased  overflow-y-auto"`}>

        <SessionProviderWrapper  session={session}>
            <Navbar />
          <main className="mt-[70px] min-h-screen ">
            {children}
          </main>

          <div className="mb-10 font-bold flex justify-center items-center gap-2 h-[20%]">
            <p className="text-sm md:text-md  text-gray-400 text-center">Build by sujay ghosh 🚀</p>
            <Link href={"https://github.com/sujaycontributer/AI-Quiz-App"} className="hover:text-gray-500 text-center">Github</Link>
            <Link href={"https://www.linkedin.com/in/sujay-ghosh-1b18a2266/"} className="hover:text-gray-500 text-center" >Linkedin</Link>
          </div>
        </SessionProviderWrapper>
        
      </body>
    </html>
  );
}
